source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'PLFormViewController_Example' do
  pod 'PLFormViewController', :path => '../'
  pod 'PLTableManager'
  pod 'PLForm'
  pod 'TPKeyboardAvoiding'

  target 'PLFormViewController_Tests' do
    inherit! :search_paths

  	pod 'Expecta'

  end
end
