source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLFormViewController_Example', :exclusive => true do
  pod "PLFormViewController", :path => "../"
end

target 'PLFormViewController_Tests', :exclusive => true do
  pod "PLFormViewController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
